version: "3.7"

services:

  # API Gateway
  nginx:
    image: signomix-proxy:local
    ports:
      - 8080:8080
      - 443:443

  # signomix
  signomix-main:
    image: signomix:local
    environment:
    # CHANGE CONFIG BELOW
      - SIGNOMIX_INITIAL_ADMIN_EMAIL=admin@localhost
      - SIGNOMIX_INITIAL_ADMIN_SECRET=test123
      - SIGNOMIX_ADMIN_NOTIFICATION_EMAIL=admin@localhost
      - SIGNOMIX_URL=http://localhost
      - SIGNOMIX_TITLE="Signomix"
      - GATRACKINGID=MY-GA-TRACKING-ID
      - SIGNOMIX_SMTP_FROM=signomix@localhost
      - SIGNOMIX_SMTP_HOST=localhost
      - SIGNOMIX_SMTP_USER=signomix@localhost
      - SIGNOMIX_SMTP_PASSWORD=my-password
      - SIGNOMIX_PUSHOVER_TOKEN=my-token
      - SIGNOMIX_TELEGRAM_TOKEN=my-token
      - SIGNOMIX_TELEGRAM_TOKEN2=my-token
      - SIGNOMIX_SMS_LOGIN=my-login
      - SIGNOMIX_SMS_PASSWORD=my-password
      - SIGNOMIX_EMAIL_FROM=signomix@localhost
      - SIGNOMIX_EMAIL_HOST=localhost
      - SIGNOMIX_EMAIL_USER=signomix@localhost
      - SIGNOMIX_EMAIL_PASSWORD=my-password
    expose:
      - 8080
    volumes:
      - ~/tests/signomix/volume-service/db:/usr/signomix/data/db:rw
      - ~/tests/signomix/volume-service/logs:/usr/signomix/data/logs:rw
      - ~/tests/signomix/volume-service/files:/usr/signomix/data/files:rw
      - ~/tests/signomix/volume-service/assets:/usr/signomix/data/assets:rw
      - ~/tests/signomix/volume-service/backup:/usr/signomix/data/backup:rw
    
  # signomix publication service
  signomix-ta-ps:
    image: signomix-ta-ps:local
    environment:
      - SIGNOMIX_TITLE='Signomix'
    expose:
      - 8080
    volumes:
      - ~/tests/signomix/volume-ps:/usr/signomix/dbdata:rw
      - ~/tests/signomix/volume-ps/logs:/usr/signomix/dbdata/logs:rw
      - ~/tests/signomix/volume-ps/assets:/usr/signomix/dbdata/assets:rw
    
  # database
  dbserver:
    image: signomix-database:local
    volumes:
      - ~/tests/signomix/volume-db:/data:rw
