version: "3.7"

services:

  # Proxy & API Gateway
  nginx:
    image: ghcr.io/signomix/signomix-proxy:latest
    depends_on:
      - signomix-main
      - signomix-ta-ps
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080
      - 443:443

  # signomix
  signomix-main:
    image: ghcr.io/signomix/signomix:latest
    depends_on:
      - signomix-database
    restart: always
    environment:
    # CHANGE CONFIG BELOW
      - SIGNOMIX_INITIAL_ADMIN_EMAIL=admin@localhost
      - SIGNOMIX_INITIAL_ADMIN_SECRET=test123
      - SIGNOMIX_ADMIN_NOTIFICATION_EMAIL=admin@localhost
      - SIGNOMIX_URL=http://localhost
      - SIGNOMIX_TITLE="Signomix"
      - GATRACKINGID=MY-GA-TRACKING-ID
      - SIGNOMIX_SMTP_FROM=signomix@localhost
      - SIGNOMIX_SMTP_HOST=localhost
      - SIGNOMIX_SMTP_USER=signomix@localhost
      - SIGNOMIX_SMTP_PASSWORD=my-password
      - SIGNOMIX_PUSHOVER_TOKEN=my-token
      - SIGNOMIX_TELEGRAM_TOKEN=my-token
      - SIGNOMIX_TELEGRAM_TOKEN2=my-token
      - SIGNOMIX_SMS_LOGIN=my-login
      - SIGNOMIX_SMS_PASSWORD=my-password
      - SIGNOMIX_EMAIL_FROM=signomix@localhost
      - SIGNOMIX_EMAIL_HOST=localhost
      - SIGNOMIX_EMAIL_USER=signomix@localhost
      - SIGNOMIX_EMAIL_PASSWORD=my-password
    expose:
      - 8080
    volumes:
      - /home/signomix/volume-service/db:/usr/signomix/dbdata/db:rw
      - /home/signomix/volume-service/logs:/usr/signomix/dbdata/logs:rw
      - /home/signomix/volume-service/files:/usr/signomix/dbdata/files:rw
      - /home/signomix/volume-service/assets:/usr/signomix/dbdata/assets:rw
      - /home/signomix/volume-service/backup:/usr/signomix/dbdata/backup:rw
    
  # signomix publication service
  signomix-ta-ps:
    image: ghcr.io/signomix/signomix-ta-ps:latest
    depends_on:
      - signomix-database    
    restart: always
    environment:
      - SIGNOMIX_TITLE='Signomix'
    expose:
      - 8080
    volumes:
      - /home/signomix/volume-ps:/usr/signomix/dbdata:rw
      - /home/signomix/volume-ps/logs:/usr/signomix/dbdata/logs:rw
      - /home/signomix/volume-ps/assets:/usr/signomix/dbdata/assets:rw
    
  # database
  signomix-database:
    image: ghcr.io/signomix/signomix-database:latest
    restart: always
    expose:
      - 9092
    volumes:
      - /home/signomix/volume-db:/h2data:rw
